name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-bld-project:
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Download dependencies [example-baseproject]
        working-directory: examples/example-baseproject
        run: ./bld download

      - name: Run tests with JaCoCo [example-baseproject]
        working-directory: examples/example-baseproject
        run: ./bld compile jacoco

      - name: Download dependencies [example-project]
        working-directory: examples/example-project
        run: ./bld download

      - name: Run tests with JaCoCo [example-project]
        working-directory: examples/example-project
        run: ./bld compile jacoco

      - name: Download dependencies
        run: ./bld download

      - name: Compile source code
        run: ./bld compile

      - name: Run tests
        id: tests
        run: ./bld test

      - name: Run reporter
        if: always() && steps.tests.outcome == 'failure'
        run: ./bld reporter --all
